name: Penga CI

env:
  AZURE_WEBAPP_NAME: penga-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
      
  build-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore API Nuget packages
      run: dotnet restore Penga.sln

    - name: Build API solution
      run: dotnet build Penga.sln --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}/app
      
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v3
      with:
        name: penga-api
        path: ${{ env.DOTNET_ROOT }}/app
      
  build-ui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install npm dependencies
      run: npm install
      working-directory: src/penga-ui
    
    - name: Build NextJS app
      run: npm run build
      working-directory: src/penga-ui
      
  deploy-api:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact from build
      uses: actions/download-artifact@v3
      with:
        name: penga-api
        
    - name: Deploy to Azure App Service
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}